#Add the below YAML:

# deploy
name: CICD using maven and SL lab 
on: 
 push: 
   branches: ["main"]
 workflow_dispatch: 
jobs: 
  buildandDeploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Clone the Repo 
      uses: actions/checkout@v4 
    - name: Setup JDK 21 and maven 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Build with Maven 
      run: mvn -B package --file pom.xml 
    - name: connect to Lab and deploy code on tomcat
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
       host: '10.232.112.164'
       user: 'Sushant'
       pass: 'Lancelot'
       port: 3389
       connect_timeout: 10s
       first_ssh: |
          sudo chmod 777 /tmp/
       scp: |
          './target/*war' => /tmp/
       last_ssh: |
          sudo systemctl restart tomcat.service 
